configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/rzp%2Fgomon-3e4db0ac936a8da1b5e93532d5cafad4b3e059c4dcb2c5cd2387996a1b84b79d.yml
openapi_spec_hash: 95ee1f70c70490cf5d7dfcf326fab00d
config_hash: fc0bcd7e0ab0cc1b76baa27bbee39606
